name: RUN-BOT

on:
  schedule:
    - cron: "30 21 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build container
        run: |
          docker build -t finovsk/guedes-offshore-bot .
          
      - name: Run the container
        env:
          KEY: ${{ secrets.KEY}}
          SECRET: ${{ secrets.SECRET }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          CREDENTIALS: ${{ secrets.CREDENTIALS }}
        run: |
          docker run -e KEY=$KEY -e SECRET=$SECRET -e CONSUMER_KEY=$CONSUMER_KEY -e CONSUMER_SECRET=$CONSUMER_SECRET -e CREDENTIALS=$CREDENTIALS finovsk/guedes-offshore-bot
