name: CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "* 13-14 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Brazil/East"

      - name: Run a one-line script
        run: echo date